# Generated by Django 4.2.8 on 2024-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="medicine",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
