# Generated by Django 4.2.8 on 2024-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="description",
            field=models.TextField(),
        ),
    ]
