# Generated by Django 4.2.8 on 2024-02-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_store", "0002_alter_medicine_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
